### ISSUE TITLE
Add hogfather support

### ISSUE THREAD

**Issue by aledeg** [Aorimn/dokuwiki-tokenbucketauth#10]
This extension does not work with the latest dokuwiki version. It could be nice to either update it or at least warn users that it will break their install.

**Comment by Aorimn** [comment]
I've not worked on this for a long time and don't have time to work on this, even though that shouldn't be that hard to port to a new DW version.

**Comment by danm14320** [comment]
the correction to be made is here (in **action.php** into tokenbucketauth)
public function register(&$controller)
by
**public function register($controller)**

it works perfectly for me

**Comment by aledeg** [comment]
@danm14320 Maybe you could make a PR for that?

**Comment by danm14320** [comment]
in fact, in the sources here, the mod had already been fixed !

**Comment by Aorimn** [comment]
Thanks for the bug report!
If it's already fixed, what made you think the extension didn't work with hogfather? Was it because you were working with a former version due to a DW upgrade?

**Comment by Aorimn** [comment]
Closing in the meantime as this doesn't look like a bug in this plugin.

**Comment by aledeg** [comment]
Sorry for the noise. It seems to work fine now. I have no idea why though. :/

**Comment by asheenlevrai** [comment]
@danm14320 

Do you have any time to look at [this](https://github.com/Aorimn/dokuwiki-tokenbucketauth/issues/12)?

Thank you very much in advance for any help you could provide.

Best,
-a-
